### ISSUE TITLE
Build failure on arch

### ISSUE THREAD

**Issue by anxiousmodernman** [redox-os/newlib#78]
Rust: rustc 1.25.0-nightly (15a1e2844 2018-01-20)

Following the for building worked up until this point.

```
# Then newlib
cd ../newlib
makepkg -si
```

The first thing I notice is a rust compiler error

![redox](https://user-images.githubusercontent.com/396004/35190756-4851bc8a-fe1e-11e7-81ed-711ce1aca563.png)

Then, things proceed, and makepkg finally terminates here:
![untilhere](https://user-images.githubusercontent.com/396004/35190759-5fe56c02-fe1e-11e7-9908-b7675c77c223.png)

**Comment by anxiousmodernman** [comment]
Standby: I've been advised to use setup.sh in the libc root instead of `makepkg` on each individual component.

**Comment by eisterman** [comment]
https://github.com/redox-os/cookbook/blob/master/README.md
The official cookbook says something else, what i need to do to properly compile the toolchain?

**Comment by Stephen-Seo** [comment]
Getting the same issue on Arch (building using the PKGBUILDS in redox-os:libc:packages/arch), I've even tried installing automake-1.11 and changing the PKGBUILD to be more similar to redox-os:libc:setup.sh . Build ends with same error as second image in the first post of this issue.

**Comment by sajattack** [comment]
@ids1024 time to update your PKGBUILDs?
